### ISSUE TITLE
Add property parameter check for PHPUnit setter fluent

### ISSUE THREAD

**Issue by Haehnchen** [bestit/PHP_CodeSniffer#14]
check atleast for a given property, this must followed by an $this->XXX usage.

eg this will:
```
\PHPUnit_Framework_TestCase::setUp
\PHPUnit\Framework\TestCase::setUp
```

reference: https://github.com/bestit/PHP_CodeSniffer/pull/10

**Comment by bestit-tkellner** [comment]
Created a JIRA Ticket
