### ISSUE TITLE
Properties with relative class names

### ISSUE THREAD

**Issue by migo315** [bestit/PHP_CodeSniffer#63]
The cs do not allow type hints for relative class names. Eg:

```
use Foobar\Config\Authentication;
use Foobar\Model\Search;
use Foobar\Model\Suggest;

class Config
{
    /**
     * @var Authentication
     */
    private $authentication;

    /**
     * @var array|Search\Panel[]
     */
    private $searchPanels;

    /**
     * @var array|Suggest\Panel[]
     */
    private $suggestPanels;
```

Error message:

>  37 | ERROR | array|Search\Panel[] is invalid. Expected format: "/^(?P<type>[\w\|\[\]]+)(?P<var> \$\w+)?$|\s/"
> 44 | ERROR | array|Suggest\Panel[] is invalid. Expected format: "/^(?P<type>[\w\|\[\]]+)(?P<var> \$\w+)?$|\s/"

**Comment by b3nl** [comment]
correct. ;)

**Comment by b3nl** [comment]
But, lets talk about change requests for the style in the office today.
