### ISSUE TITLE
Slevomat's ParameterTypeHint throws errors for nullable typehints

### ISSUE THREAD

**Issue by stefanhaelingbestit** [bestit/PHP_CodeSniffer#69]
In Version 1.x, when a function has annotations that suggest a parameter has a nullable type, the PHPCS demands Parameter Typehints.

    /**
     * @param string|null $parameter
     *
     * @return bool true = request param is string and not empty
     */
    public function representativeFunctionName($parameter): bool
    {
        if ($parameter){
            return true;
        }
    }

10 | ERROR | [x] Method \{Path}::representativeFunctionName() does not have parameter type hint for its parameter $parameter but it should be possible to add it based on @param annotation "string|null". (SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingParameterTypeHint)

**Comment by b3nl** [comment]
Two solutions without further research:
1. public function representativeFunctionName(string $parameter = null)
2. @param mixed

Maybe this error is correct and should force you to create better style ;) ?
