### ISSUE TITLE
CBF messes up @ORM-Annotations

### ISSUE THREAD

**Issue by stefanhaelingbestit** [bestit/PHP_CodeSniffer#70]
Variable's docblock with @ORM-tag being tested as

     * @var Collection containing article models
     *
     * @ORM\ManyToMany(targetEntity="Shopware\Models\Article\Detail")
     * @ORM\JoinTable(name="bestit_genius_offering_related_article",
     *      joinColumns={
     *          @ORM\JoinColumn(
     *              name="offering",
     *              referencedColumnName="id"
     *          )
     *      },
     *      inverseJoinColumns={
     *          @ORM\JoinColumn(
     *              name="article",
     *              referencedColumnName="id"
     *          )
     *      }
     * )
     */

results in output of phpcs:

117 | WARNING | [x] Please provide the tags in occurrence and then alphabetical order 
     |         |             (a-z) but with return at last position. (BestIt.DocTags.TagSorting.WrongTagSorting)
 122 | ERROR   | [ ] Please remove unnecessary whitespace. (BestIt.Commenting.RedundantWhitespace.RedundantWhitespace)
 128 | ERROR   | [ ] Please remove unnecessary whitespace. (BestIt.Commenting.RedundantWhitespace.RedundantWhitespace)
 135 | WARNING | [ ] Please sort you contents alphabetically. (BestIt.Formatting.AlphabeticClassContent.SortAlphabetically)

Upon autofixing using phpcbf:

     * @ORM\JoinTable(name="bestit_genius_offering_related_article", joinColumns={
     * @ORM\ManyToMany(targetEntity="Shopware\Models\Article\Detail")
     * @var Collection containing article models
              *
              * @ORM\JoinColumn( name="offering", referencedColumnName="id" ) }, inverseJoinColumns={
              * @ORM\JoinColumn( name="article", referencedColumnName="id" ) } )
              */

**Comment by b3nl** [comment]
Will be done asap in 1.2.2 and 2.0.2.
