### ISSUE TITLE
Type declarations are not compatible with squizlabs/php_codesniffer:3.5.4

### ISSUE THREAD

**Issue by avareldev** [bestit/PHP_CodeSniffer#76]
According to the composer dependencies squizlabs/php_codesniffer:3.5.4 is a valid dependency version, but using it with best-it/php_codesniffer:2.0.3 throws a type declaration error in the File Decorator.

`----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been
   |       | aborted. The error message was: Declaration of
   |       | BestIt\CodeSniffer\AbstractFileDecorator::getCondition($stackPtr,
   |       | $type) should be compatible with
   |       | PHP_CodeSniffer\Files\File::getCondition($stackPtr,
   |       | $type, $first = true) in
   |       | /opt/atlassian/pipelines/agent/build/vendor/best-it/php_codesniffer/src/Standards/BestIt/CodeSniffer/AbstractFileDecorator.php
   |       | on line 426
----------------------------------------------------------------------`

**Comment by b3nl** [comment]
Fixxed in 858b1d151b2a41a9cc7eee5317f8085db41e09e8 (3.0.0) and 8c21627d9d0569622a33908ec7ea02df486c24c3 (2.0.4).
